[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd materi-backend && npm ci']

[phases.build]
cmds = ['cd materi-backend && npx prisma generate']

[start]
cmd = 'cd materi-backend && node index.js'
